[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  node_bundle = true
  included_files = ["views/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
